# Generated by Django 6.0.5 on 2026-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('image', models.ImageField(upload_to='certifications/')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
